services:
  redis:
    image: redis:7-alpine

  backend:
    image: gunoo4/kkotuli-backend:latest
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATA_REDIS_HOST=redis
      - DICTIONARY_API_KEY=${DICTIONARY_API_KEY}
    depends_on:
      - redis

  frontend:
    image: gunoo4/kkotuli-frontend:latest
    ports:
      - "80:80"
    depends_on:
      - backend